API sorts reports by latest first
squaredev-io/whitebox pull request #129
Opened 2023-02-10 13:29 UTC by sinnec

2023-02-10 13:50 UTC, NickNtamp requested changes
@sinnec I think that descending is not the desired order if I am not mistaken. We want the oldest report to be on the top of the list. Can you please recheck it and confirm?

2023-02-10 14:08 UTC, sinnec commented
> @sinnec I think that descending is not the desired order if I am not mistaken. We want the oldest report to be on the top of the list. Can you please recheck it and confirm?

Yes, your're right. I thought it shoould be latest first.

2023-02-11 13:43 UTC, momegas approved these changes

2023-02-12 11:45 UTC, NickNtamp approved these changes

2023-02-12 11:46 UTC, merged